export const ADD_PRODUCT = "product/ADD_PRODUCT";
export const ADD_CART_TO_REDUCE_QUANTITY =
  "product/ADD_CART_TO_REDUCE_QUANTITY";
export const ADD_CART_TO_INCREASE_QUANTITY =
  "product/ADD_CART_TO_INCREASE_QUANTITY";
export const REMOVE_BTN_QUANTITY_MAINTAIN =
  "product/REMOVE_BTN_QUANTITY_MAINTAIN";
